---
- hosts: all
  become: yes

  vars:
    page_title: My Landign Page
    page_description: This is my landing page description.

  tasks:
    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: latest

    - name: Apply Page Template
      ansible.builtin.template:
        src: files/landing-page.html.j2
        dest: /var/www/html/index.nginx-debian.html

    - name: Allow all access to tcp port 80
      ansible.builtin.ufw:
        rule: allow
        port: '80'
        proto: tcp
