---
- hosts: all
  become: yes
  
  vars:
    application_list:
      - vim 
      - curl
      - unzip
      - tmux

  tasks:
    - name: Update apt cache and make sure that application follow list are installed
      ansible.builtin.apt:
        name: "{{ application_list }}"
        update_cache: yes
